language: python
python:
    - "2.7"

before_script:
    - wget https://googleappengine.googlecode.com/files/google_appengine_1.9.24.zip -nv
    - unzip -q google_appengine_1.9.24.zip
    - make setup-build

install: "pip install -r requirements.txt --use-mirrors"

script:
    - make build
